![Python Image](https://www.python.org/static/community_logos/python-logo-inkscape.svg)

<div align="center">
    <h1>Tutorial Python 3</h1>
</div>

<div align="center">
    <h3>Written by: Aulia Khalqillah, S.Si., M.Si</h3>
</div>

## Table of Contents

[Working With Libraries](#Working-With-Libraries)

- [1. Numpy](#1.-Numpy)
    * [Generate Array](#Generate-Array)
    * [Array Index](#Array-Index)
    * [Generate Random Array](#Generate-Random-Array)
        + [1. One Dimensional Array](#1.-One-Dimensional-Array)
        + [2. Two Domensional Array](#2.-Two-Dimensional-Array)
    * [Modification an Array](#Modification-an-Array)
        + [Change Element of 1D Array](#Change-element-of-1D-array)
        + [Change Element of 2D Array](#Change-element-of-2D-array)
    * [Slice an Array](#Slice-an-Array)
        + [1D Array](#1.-1D-Array)
        + [2D Array](#2.-2D-Array)
    * [Basic Mathematical Operation](#Basic-Mathematical-Operation)
    * [More Numpy's Methods](#More-Numpy's-Methods)

## Working With Libraries
### 1. Numpy
Import a numpy library by type the following command

In [1]:
import numpy as np

The `np` in command above is the alias of numpy library that I write. This alias can be modified with any alias name. So, we just type `np.(method)` to call a method from numpy library. 

#### Generate Array

I'm going to create an array by using two method that are `arange` method and `linspace` method.

##### a. arange

The format of `np.arange` is `np.arange(start, stop, step)`. For example, I generate an array without using `step` and the result will be asign to `arr` variable as follows

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

with `step` where the value is 2 and I assign the result to `arr_step` variable

In [3]:
arr_step = np.arange(0,10,2)
arr_step

array([0, 2, 4, 6, 8])

the result is even array.

##### b. linspace

Now, I'm going to generate an array by using `linspace` method. The format of `np.linspace` is `np.linspace(start,stop,length of data)`. First, I generate an array without input a length of data and I assign the result to `arr_linspace` variable as follows

In [4]:
arr_linspace = np.linspace(0,0.5)
arr_linspace

array([0.        , 0.01020408, 0.02040816, 0.03061224, 0.04081633,
       0.05102041, 0.06122449, 0.07142857, 0.08163265, 0.09183673,
       0.10204082, 0.1122449 , 0.12244898, 0.13265306, 0.14285714,
       0.15306122, 0.16326531, 0.17346939, 0.18367347, 0.19387755,
       0.20408163, 0.21428571, 0.2244898 , 0.23469388, 0.24489796,
       0.25510204, 0.26530612, 0.2755102 , 0.28571429, 0.29591837,
       0.30612245, 0.31632653, 0.32653061, 0.33673469, 0.34693878,
       0.35714286, 0.36734694, 0.37755102, 0.3877551 , 0.39795918,
       0.40816327, 0.41836735, 0.42857143, 0.43877551, 0.44897959,
       0.45918367, 0.46938776, 0.47959184, 0.48979592, 0.5       ])

In [5]:
len(arr_linspace)

50

as we can see, the array has been generated start from 0 to 0.5 in 50 length of data as default configuration. Next, I generate an array with input a length of data e.g. 70 values and I assign the result to `arr_linspace_length` variable as follows

In [6]:
arr_linspace_length = np.linspace(0,0.5,70)
arr_linspace_length

array([0.        , 0.00724638, 0.01449275, 0.02173913, 0.02898551,
       0.03623188, 0.04347826, 0.05072464, 0.05797101, 0.06521739,
       0.07246377, 0.07971014, 0.08695652, 0.0942029 , 0.10144928,
       0.10869565, 0.11594203, 0.12318841, 0.13043478, 0.13768116,
       0.14492754, 0.15217391, 0.15942029, 0.16666667, 0.17391304,
       0.18115942, 0.1884058 , 0.19565217, 0.20289855, 0.21014493,
       0.2173913 , 0.22463768, 0.23188406, 0.23913043, 0.24637681,
       0.25362319, 0.26086957, 0.26811594, 0.27536232, 0.2826087 ,
       0.28985507, 0.29710145, 0.30434783, 0.3115942 , 0.31884058,
       0.32608696, 0.33333333, 0.34057971, 0.34782609, 0.35507246,
       0.36231884, 0.36956522, 0.37681159, 0.38405797, 0.39130435,
       0.39855072, 0.4057971 , 0.41304348, 0.42028986, 0.42753623,
       0.43478261, 0.44202899, 0.44927536, 0.45652174, 0.46376812,
       0.47101449, 0.47826087, 0.48550725, 0.49275362, 0.5       ])

to check the length of data, you can type the `len(variable name)` function as follows

#### Generate 'Zeros' Element of  Array

We can easy to generate an array that contain of zero by using `np.zeros(length of data)` method. For example, I generate a zero array for 10 length of data as follows

In [72]:
arr_zeros = np.zeros(10)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Generate 'Ones' Element of Array

The same way when we want to generate an array that contain element of 1 for entire array element by using `np.ones(length of data)` method. For example

In [78]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Array Index

We already have generate an array as previous methods. Now, if we want to access a specific value in the array, we have to identify its index number. In Python, the first index number is started from 0, the second index is 1 and so on. For example, we use a variable of `arr_linspace_length` to get a specific value from the second index which is 1. By typing the following command where the index number is written inside a bracket.

In [7]:
arr_linspace_length[1]

0.007246376811594203

_**Remember, in Python, the first index is started from 0**_. 

We can take the last value from `arr_linspace_length` variable as follows command

In [8]:
arr_linspace_length[69]

0.5

where the 69 is the last index of this array. For the simplicity, the last index number is `the length of data - 1`. If we want to take a value from index number of 10, we can type

In [9]:
arr_linspace_length[10]

0.07246376811594203

#### Generate Random Array

##### 1. One Dimensional Array

Numpy has a random method to generate a random array values. The format to call this method is `np.random.(method)(length of data)`. Generally, there are three methods in random class, `rand`, `randn`, and `randint`. 

1. `rand(row,col)`    : generate a standard random array.
2. `randn(row,col)`   : generate a random array based on normal distribution.
3. `randint(low, high=None, size=None)` : generate a single integer random number as default.

In [10]:
arr_random = np.random.rand(5)
arr_random

array([0.1887854 , 0.84878078, 0.78399138, 0.72841803, 0.20378705])

In [11]:
arr_randn = np.random.randn(5)
arr_randn

array([ 0.14419313,  0.98326896,  0.56147786, -0.0556791 , -1.09470422])

In [12]:
arr_randint = np.random.randint(2,5,size=10)
arr_randint

array([3, 3, 3, 4, 4, 2, 4, 2, 2, 3])

##### 2. Two Dimensional Array

We have done to generate a 1D array. Next, we generate a 2D array by using numpy library. To do this, we apply an `array` method as the following command.

In [13]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Now, we have 2D array that means we have 2 rows and 5 columns. By using array method, we have to set the element of array manually as above command. We can use a `random.rand()` or `random.randn()` method to generate a 2D array. 

In [14]:
arr_2d_random = np.random.rand(5,5)
arr_2d_random

array([[0.16860543, 0.47153478, 0.3196002 , 0.7668874 , 0.50581538],
       [0.95733368, 0.86891484, 0.41191144, 0.12408419, 0.77419912],
       [0.18129179, 0.66731457, 0.0018552 , 0.63769256, 0.9320652 ],
       [0.11947688, 0.2019806 , 0.43238339, 0.16536263, 0.47368182],
       [0.31062916, 0.59056527, 0.36895061, 0.15685153, 0.91627449]])

#### Modification an Array

##### Change element of 1D array
An element in an array can be modified or changed to another value. For example, we use `arr_random` variable that has been created previously.

In [15]:
arr_random

array([0.1887854 , 0.84878078, 0.78399138, 0.72841803, 0.20378705])

We take a value which in the third index or equal to index number of 2 as follows

In [16]:
arr_random[2]

0.7839913813262193

and to change this value (e.g. 100), we can write the following command

In [17]:
arr_random[2] = 100
arr_random

array([  0.1887854 ,   0.84878078, 100.        ,   0.72841803,
         0.20378705])

and now, the value has been changed.

##### Change element of 2D array

We have generated a 2D array that assign to `arr_2d` and `arr_2d_random` variables. To show an element of 2D array, we use the format `variable[row index][column index]`. Let's use the `arr_2d` variable for example.

In [18]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

We want to take a value of 4 from the `arr_2d` variable. The value of 4 is in the first row (index of 0) and the forth column (index of 3). Then, we get this value and assign to `value` variable by using command bellow

In [19]:
value = arr_2d[0][3]
value

4

To change this element just type

In [20]:
arr_2d[0][3] = 10
arr_2d

array([[ 1,  2,  3, 10,  5],
       [ 6,  7,  8,  9, 10]])

the value of 4 has been changed become 10.

#### Slice an Array

##### 1. 1D Array

We can slice a few element of an array based on its index. We use 

1. `variable[:index number]` to slice all values in array from first index to index number (the index number is not include in the result),
2. `variable[index number:]` to slice all values in array an array from index number to end of index and
3. `variable[start index number: stop index number]` to slice an array in between index number (the stop index number is not include in the result)

Let's try to `arr_random` variable to apply this slice methods.

In [21]:
arr_slice_first = arr_random[:3]
arr_slice_first

array([  0.1887854 ,   0.84878078, 100.        ])

In [22]:
arr_slice_end = arr_random[3:]
arr_slice_end

array([0.72841803, 0.20378705])

In [23]:
arr_slice_between = arr_random[2:4]
arr_slice_between

array([100.        ,   0.72841803])

##### 2. 2D Array

We are going further to slice 2D array from `arr_2d` variable and get a sub array from it.

In [24]:
arr_2d

array([[ 1,  2,  3, 10,  5],
       [ 6,  7,  8,  9, 10]])

We want to get the element of 2D array of 1, 2, 6 and 7 where:
    
    - the value of 1 is in the first row (index of 0) and the first column (index of 0),
    - the value of 2 is in the first row (index of 0) and the second column (index of 1),
    - the value of 6 is in the second row (index of 1) and the first column (index of 0),
    - the value of 7 is in the second row (index of 1) and the second column (index of 1).
  
 Then we can assign these values to `arr_2d_new` as follows

In [25]:
arr_2d_new = arr_2d[0:2,0:2]
arr_2d_new

array([[1, 2],
       [6, 7]])

_Remember that, to get the last value of each dimensional (e.g. 2 and 7 these values are in the second index of column which is index of 1 in Python order. So, the index number that you have to write to slice it is 1+1=2)_

#### Basic Mathematical Operation

We can apply basic mathematical operation in array, such as summation, subtraction, multiplication and division. In Python, array can be calculated directly with another array or value. For example, we use `arr_randint` variable that has been created previous [sub-chapter](#1.-One-Dimensional-Array).

In [26]:
arr_randint

array([3, 3, 3, 4, 4, 2, 4, 2, 2, 3])

Then, we create a new array that has same size with `arr_randint` which is 10.

In [27]:
arr_new = np.random.randint(1,10,size=10)
arr_new

array([4, 3, 3, 9, 7, 5, 9, 8, 6, 8])

##### Summation and Subtraction

To add these two arrays, we can apply a simple way

In [28]:
arr_addition = arr_randint + arr_new
arr_addition

array([ 7,  6,  6, 13, 11,  7, 13, 10,  8, 11])

and to suctraction

In [29]:
arr_subtraction = arr_randint - arr_new
arr_subtraction

array([-1,  0,  0, -5, -3, -3, -5, -6, -4, -5])

Then, we add the `arr_randint` with a value = 5

In [30]:
value = 5

In [31]:
arr_addition_value = arr_randint + value
arr_addition_value

array([8, 8, 8, 9, 9, 7, 9, 7, 7, 8])

and subtraction

In [32]:
arr_subtraction_value = arr_randint - value
arr_subtraction_value

array([-2, -2, -2, -1, -1, -3, -1, -3, -3, -2])

##### Multiplication and Division

Next, we apply a multiplication in these two arrays (`arr_randint` and `arr_new`)

In [33]:
arr_multiplication = arr_randint * arr_new
arr_multiplication

array([12,  9,  9, 36, 28, 10, 36, 16, 12, 24])

The multiplication process between two arrays will multiply for each pair element and this process also applies in division process

In [34]:
arr_division = arr_randint / arr_new
arr_division

array([0.75      , 1.        , 1.        , 0.44444444, 0.57142857,
       0.4       , 0.44444444, 0.25      , 0.33333333, 0.375     ])

The multiplication or division of array with a value also can be applied, where

In [35]:
value

5

In [36]:
arr_multiplication_value = arr_randint * value
arr_multiplication_value

array([15, 15, 15, 20, 20, 10, 20, 10, 10, 15])

In [37]:
arr_division_value = arr_randint / value
arr_division_value

array([0.6, 0.6, 0.6, 0.8, 0.8, 0.4, 0.8, 0.4, 0.4, 0.6])

##### Trigonometry

The numpy library has a method to calculate trigonometry cases, such as sin, cos tan and much more. For example,

In [45]:
mat_sin = np.sin(90)
mat_sin

0.8939966636005579

as we can see, the result of sin(90) is 0.89 in degree unit. If we want to get the result in radian unit, we have to convert it by multiply `np.pi/180` as follows

In [56]:
mat_sin_degree = np.sin(90*(np.pi/180))
mat_sin_degree

1.0

we also can calculate the inverse of sin to degree unit by multiply the radian with `180/np.i` as follows

In [70]:
mat_inv_sin_degree = np.arcsin(1)*(180/np.pi)
mat_inv_sin_degree

90.0

the constant of pi is called by `np.pi` from numpy library.

### More Numpy's Methods

You can find out more the methods in Numpy library by type `dir(np)` in Python shell or this notebook if you use its alias.

In [81]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',