<img align="left" width="1000" height="250" src="https://www.python.org/static/community_logos/python-logo-inkscape.svg">

<div align="left">
    <h1>Tutorial Python 3</h1>
</div>

<div align="left">
    <h3>Written by: Aulia Khalqillah, S.Si., M.Si</h3>
</div>

## Table of Contents

[Working With Libraries](#Working-With-Libraries)

- [1. Numpy](#1.-Numpy)
    * [Generate Array](#Generate-Array)
    * [Array Index](#Array-Index)
    * [Generate Random Array](#Generate-Random-Array)
        + [1. One Dimensional Array](#1.-One-Dimensional-Array)
        + [2. Two Domensional Array](#2.-Two-Dimensional-Array)
    * [Modification an Array](#Modification-an-Array)
        + [Change Element of 1D Array](#Change-element-of-1D-array)
        + [Change Element of 2D Array](#Change-element-of-2D-array)
    * [Slice an Array](#Slice-an-Array)
        + [1D Array](#1.-1D-Array)
        + [2D Array](#2.-2D-Array)
    * [Basic Mathematical Operation](#Basic-Mathematical-Operation)
    * [More Numpy's Methods](#More-Numpy's-Methods)
 
 
- [2. Pandas](#2.-Pandas)
    * [Read CSV File](#Read-CSV-File)
    * [Get an Information File](#Get-an-Information-File)
    * [Remove a Certain Data](#Remove-a-Certain-Data)
    * [Select Some of Data](#Select-Some-of-Data)
    * [Modify an Attribute of Data](#Modify-an-Attribute-of-Data)
        + [Rename a Column Name](#Rename-a-Column-Name)
        + [Change a String Fromat](#Change-a-String-Format)
        + [Time Modification](#Time-Modification)
        + [Data Sorting](#Data-Sorting)

## Working With Libraries
### 1. Numpy
Import a numpy library by type the following command

In [1]:
import numpy as np

The `np` in command above is the alias of numpy library that I write. This alias can be modified with any alias name. So, we just type `np.(method)` to call a method from numpy library. 

#### Generate Array

I'm going to create an array by using two method that are `arange` method and `linspace` method.

##### a. arange

The format of `np.arange` is `np.arange(start, stop, step)`. For example, I generate an array without using `step` and the result will be asign to `arr` variable as follows

In [3]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_step = np.arange(0,10,2)
arr_step

array([0, 2, 4, 6, 8])

the result is even array.

##### b. linspace

Now, I'm going to generate an array by using `linspace` method. The format of `np.linspace` is `np.linspace(start,stop,length of data)`. First, I generate an array without input a length of data and I assign the result to `arr_linspace` variable as follows

In [ ]:
arr_linspace = np.linspace(0,0.5)
arr_linspace

array([0.        , 0.01020408, 0.02040816, 0.03061224, 0.04081633,
       0.05102041, 0.06122449, 0.07142857, 0.08163265, 0.09183673,
       0.10204082, 0.1122449 , 0.12244898, 0.13265306, 0.14285714,
       0.15306122, 0.16326531, 0.17346939, 0.18367347, 0.19387755,
       0.20408163, 0.21428571, 0.2244898 , 0.23469388, 0.24489796,
       0.25510204, 0.26530612, 0.2755102 , 0.28571429, 0.29591837,
       0.30612245, 0.31632653, 0.32653061, 0.33673469, 0.34693878,
       0.35714286, 0.36734694, 0.37755102, 0.3877551 , 0.39795918,
       0.40816327, 0.41836735, 0.42857143, 0.43877551, 0.44897959,
       0.45918367, 0.46938776, 0.47959184, 0.48979592, 0.5       ])

to check the length of data, you can type the `len(variable name)` function as follows

In [ ]:
len(arr_linspace)

50

as we can see, the array has been generated start from 0 to 0.5 in 50 length of data as default configuration. Next, I generate an array with input a length of data e.g. 70 values and I assign the result to `arr_linspace_length` variable as follows

In [ ]:
arr_linspace_length = np.linspace(0,0.5,70)
arr_linspace_length

array([0.        , 0.00724638, 0.01449275, 0.02173913, 0.02898551,
       0.03623188, 0.04347826, 0.05072464, 0.05797101, 0.06521739,
       0.07246377, 0.07971014, 0.08695652, 0.0942029 , 0.10144928,
       0.10869565, 0.11594203, 0.12318841, 0.13043478, 0.13768116,
       0.14492754, 0.15217391, 0.15942029, 0.16666667, 0.17391304,
       0.18115942, 0.1884058 , 0.19565217, 0.20289855, 0.21014493,
       0.2173913 , 0.22463768, 0.23188406, 0.23913043, 0.24637681,
       0.25362319, 0.26086957, 0.26811594, 0.27536232, 0.2826087 ,
       0.28985507, 0.29710145, 0.30434783, 0.3115942 , 0.31884058,
       0.32608696, 0.33333333, 0.34057971, 0.34782609, 0.35507246,
       0.36231884, 0.36956522, 0.37681159, 0.38405797, 0.39130435,
       0.39855072, 0.4057971 , 0.41304348, 0.42028986, 0.42753623,
       0.43478261, 0.44202899, 0.44927536, 0.45652174, 0.46376812,
       0.47101449, 0.47826087, 0.48550725, 0.49275362, 0.5       ])

We can also convert an array data type to list data type as follows

In [ ]:
list(arr_linspace)

[0.0,
 0.01020408163265306,
 0.02040816326530612,
 0.030612244897959183,
 0.04081632653061224,
 0.0510204081632653,
 0.061224489795918366,
 0.07142857142857142,
 0.08163265306122448,
 0.09183673469387754,
 0.1020408163265306,
 0.11224489795918366,
 0.12244897959183673,
 0.13265306122448978,
 0.14285714285714285,
 0.1530612244897959,
 0.16326530612244897,
 0.17346938775510204,
 0.18367346938775508,
 0.19387755102040816,
 0.2040816326530612,
 0.21428571428571427,
 0.22448979591836732,
 0.2346938775510204,
 0.24489795918367346,
 0.25510204081632654,
 0.26530612244897955,
 0.2755102040816326,
 0.2857142857142857,
 0.29591836734693877,
 0.3061224489795918,
 0.31632653061224486,
 0.32653061224489793,
 0.336734693877551,
 0.3469387755102041,
 0.3571428571428571,
 0.36734693877551017,
 0.37755102040816324,
 0.3877551020408163,
 0.39795918367346933,
 0.4081632653061224,
 0.4183673469387755,
 0.42857142857142855,
 0.4387755102040816,
 0.44897959183673464,
 0.4591836734693877,
 0.4693877551020408

#### Generate 'Zeros' Element of  Array

We can easy to generate an array that contain of zero by using `np.zeros(length of data)` method. For example, I generate a zero array for 10 length of data as follows

In [ ]:
arr_zeros = np.zeros(10)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Generate 'Ones' Element of Array

The same way when we want to generate an array that contain element of 1 for entire array element by using `np.ones(length of data)` method. For example

In [ ]:
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Array Index

We already have generate an array as previous methods. Now, if we want to access a specific value in the array, we have to identify its index number. In Python, the first index number is started from 0, the second index is 1 and so on. For example, we use a variable of `arr_linspace_length` to get a specific value from the second index which is 1. By typing the following command where the index number is written inside a bracket.

In [ ]:
arr_linspace_length[1]

0.007246376811594203

_**Remember, in Python, the first index is started from 0**_. 

We can take the last value from `arr_linspace_length` variable as follows command

In [ ]:
arr_linspace_length[69]

0.5

where the 69 is the last index of this array. For the simplicity, the last index number is `the length of data - 1`. If we want to take a value from index number of 10, we can type

In [ ]:
arr_linspace_length[10]

0.07246376811594203

#### Generate Random Array

##### 1. One Dimensional Array

Numpy has a random method to generate a random array values. The format to call this method is `np.random.(method)(length of data)`. Generally, there are three methods in random class, `rand`, `randn`, and `randint`. 

1. `rand(row,col)`    : generate a standard random array.
2. `randn(row,col)`   : generate a random array based on normal distribution.
3. `randint(low, high=None, size=None)` : generate a single integer random number as default.

In [ ]:
arr_random = np.random.rand(5)
arr_random

array([0.0597942 , 0.43665863, 0.31475775, 0.36632682, 0.9136528 ])

In [ ]:
arr_randn = np.random.randn(5)
arr_randn

array([-1.63633259, -1.20869251,  1.02397941,  0.08078858, -0.45452591])

In [ ]:
arr_randint = np.random.randint(2,5,size=10)
arr_randint

array([4, 2, 3, 4, 4, 2, 2, 4, 4, 2])

##### 2. Two Dimensional Array

We have done to generate a 1D array. Next, we generate a 2D array by using numpy library. To do this, we apply an `array` method as the following command.

In [ ]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Now, we have 2D array that means we have 2 rows and 5 columns. By using array method, we have to set the element of array manually as above command. We can use a `random.rand()` or `random.randn()` method to generate a 2D array. 

In [ ]:
arr_2d_random = np.random.rand(5,5)
arr_2d_random

array([[0.06041188, 0.46824881, 0.27848492, 0.43939302, 0.23156948],
       [0.83099545, 0.93557565, 0.24911599, 0.32273711, 0.16268538],
       [0.6891951 , 0.68294689, 0.42855669, 0.98389189, 0.85673664],
       [0.92547451, 0.12210899, 0.5244153 , 0.44107802, 0.65407268],
       [0.82954825, 0.10401751, 0.35226337, 0.18574262, 0.20665535]])

#### Modification an Array

##### Change element of 1D array
An element in an array can be modified or changed to another value. For example, we use `arr_random` variable that has been created previously.

In [ ]:
arr_random

We take a value which in the third index or equal to index number of 2 as follows

In [ ]:
arr_random[2]

0.31475775379298265

and to change this value (e.g. 100), we can write the following command

In [ ]:
arr_random[2] = 100
arr_random

array([5.97942029e-02, 4.36658629e-01, 1.00000000e+02, 3.66326819e-01,
       9.13652796e-01])

and now, the value has been changed.

##### Change element of 2D array

We have generated a 2D array that assign to `arr_2d` and `arr_2d_random` variables. To show an element of 2D array, we use the format `variable[row index][column index]`. Let's use the `arr_2d` variable for example.

In [ ]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

We want to take a value of 4 from the `arr_2d` variable. The value of 4 is in the first row (index of 0) and the forth column (index of 3). Then, we get this value and assign to `value` variable by using command bellow

In [ ]:
value = arr_2d[0][3]
value

4

To change this element just type

In [ ]:
arr_2d[0][3] = 10
arr_2d

array([[ 1,  2,  3, 10,  5],
       [ 6,  7,  8,  9, 10]])

the value of 4 has been changed become 10.

#### Slice an Array

##### 1. 1D Array

We can slice a few element of an array based on its index. We use 

1. `variable[:index number]` to slice all values in array from first index to index number (the index number is not include in the result),
2. `variable[index number:]` to slice all values in array an array from index number to end of index and
3. `variable[start index number: stop index number]` to slice an array in between index number (the stop index number is not include in the result)

Let's try to `arr_random` variable to apply this slice methods.

In [ ]:
arr_slice_first = arr_random[:3]
arr_slice_first

array([5.97942029e-02, 4.36658629e-01, 1.00000000e+02])

In [ ]:
arr_slice_end = arr_random[3:]
arr_slice_end

array([0.36632682, 0.9136528 ])

In [ ]:
arr_slice_between = arr_random[2:4]
arr_slice_between

array([100.        ,   0.36632682])

##### 2. 2D Array

We are going further to slice 2D array from `arr_2d` variable and get a sub array from it.

In [ ]:
arr_2d

array([[ 1,  2,  3, 10,  5],
       [ 6,  7,  8,  9, 10]])

We want to get the element of 2D array of 1, 2, 6 and 7 where:
    
    - the value of 1 is in the first row (index of 0) and the first column (index of 0),
    - the value of 2 is in the first row (index of 0) and the second column (index of 1),
    - the value of 6 is in the second row (index of 1) and the first column (index of 0),
    - the value of 7 is in the second row (index of 1) and the second column (index of 1).
  
 Then we can assign these values to `arr_2d_new` as follows

In [ ]:
arr_2d_new = arr_2d[0:2,0:2]
arr_2d_new

array([[1, 2],
       [6, 7]])

_Remember that, to get the last value of each dimensional (e.g. 2 and 7 these values are in the second index of column which is index of 1 in Python order. So, the index number that you have to write to slice it is 1+1=2)_

#### Basic Mathematical Operation

We can apply basic mathematical operation in array, such as summation, subtraction, multiplication and division. In Python, array can be calculated directly with another array or value. For example, we use `arr_randint` variable that has been created previous [sub-chapter](#1.-One-Dimensional-Array).

In [ ]:
arr_randint

array([4, 2, 3, 4, 4, 2, 2, 4, 4, 2])

Then, we create a new array that has same size with `arr_randint` which is 10.

In [ ]:
arr_new = np.random.randint(1,10,size=10)
arr_new

array([1, 3, 3, 1, 4, 3, 3, 8, 6, 7])

##### Summation and Subtraction

To add these two arrays, we can apply a simple way

In [ ]:
arr_addition = arr_randint + arr_new
arr_addition

array([ 5,  5,  6,  5,  8,  5,  5, 12, 10,  9])

and to suctraction

In [ ]:
arr_subtraction = arr_randint - arr_new
arr_subtraction

array([ 3, -1,  0,  3,  0, -1, -1, -4, -2, -5])

Then, we add the `arr_randint` with a value = 5

In [ ]:
value = 5

In [ ]:
arr_addition_value = arr_randint + value
arr_addition_value

array([9, 7, 8, 9, 9, 7, 7, 9, 9, 7])

and subtraction

In [ ]:
arr_subtraction_value = arr_randint - value
arr_subtraction_value

array([-1, -3, -2, -1, -1, -3, -3, -1, -1, -3])

##### Multiplication and Division

Next, we apply a multiplication in these two arrays (`arr_randint` and `arr_new`)

In [ ]:
arr_multiplication = arr_randint * arr_new
arr_multiplication

array([ 4,  6,  9,  4, 16,  6,  6, 32, 24, 14])

The multiplication process between two arrays will multiply for each pair element and this process also applies in division process

In [ ]:
arr_division = arr_randint / arr_new
arr_division

array([4.        , 0.66666667, 1.        , 4.        , 1.        ,
       0.66666667, 0.66666667, 0.5       , 0.66666667, 0.28571429])

The multiplication or division of array with a value also can be applied, where

In [ ]:
value

5

In [ ]:
arr_multiplication_value = arr_randint * value
arr_multiplication_value

array([20, 10, 15, 20, 20, 10, 10, 20, 20, 10])

In [ ]:
arr_division_value = arr_randint / value
arr_division_value

array([0.8, 0.4, 0.6, 0.8, 0.8, 0.4, 0.4, 0.8, 0.8, 0.4])

##### Trigonometry

The numpy library has a method to calculate trigonometry cases, such as sin, cos tan and much more. For example,

In [ ]:
mat_sin = np.sin(90)
mat_sin

0.8939966636005579

as we can see, the result of sin(90) is 0.89 in degree unit. If we want to get the result in radian unit, we have to convert it by multiply `np.pi/180` as follows

In [ ]:
mat_sin_degree = np.sin(90*(np.pi/180))
mat_sin_degree

1.0

we also can calculate the inverse of sin to degree unit by multiply the radian with `180/np.i` as follows

In [ ]:
mat_inv_sin_degree = np.arcsin(1)*(180/np.pi)
mat_inv_sin_degree

90.0

the constant of pi is called by `np.pi` from numpy library.

### More Numpy's Methods

You can find out more the methods in Numpy library by type `dir(np)` in Python shell or this notebook if you use its alias.

In [ ]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

### 2. Pandas

[Pandas](https://pandas.pydata.org/) is one of many Python libraries. This library is very helpful when we are working with a sturcture data such as in CSV/Excel file format. We can easily read a file that containt a lot of data. Firts, we have to import the Pandas and write the `pd` as its alias.

#### Read CSV File

In [ ]:
import pandas as pd

In this case, I use an earthquake data around Aceh that I downloaded from [Earthquake Catalog of USGS](https://earthquake.usgs.gov/earthquakes/search/). I name this file as `earthquake_aceh_usgs.csv`. I am going to read this file by using `pd.read_csv` method from Pandas and I assign this file to `data` variable as follows

In [ ]:
data = pd.read_csv('earthquake_aceh_usgs.csv')
data

time  latitude  longitude   depth  mag magType  nst  \
0   2021-05-02T20:49:43.322Z    5.3234    94.6170   63.97  5.0      mb  NaN   
1   2021-05-02T13:02:17.751Z    4.0461    95.7566   50.03  4.6      mb  NaN   
2   2021-04-17T01:04:53.776Z    5.1158    95.4508  100.74  5.0     mww  NaN   
3   2021-04-09T15:14:31.108Z    4.8116    96.2611   27.57  4.3      mb  NaN   
4   2021-04-09T08:08:58.946Z    3.0723    96.3738   55.17  4.2      mb  NaN   
5   2021-04-08T17:40:42.267Z    3.7847    95.7753   66.13  4.4      mb  NaN   
6   2021-04-06T02:36:30.481Z    4.2645    96.0982   67.22  4.0      mb  NaN   
7   2021-03-24T06:44:29.347Z    5.1787    94.3998   54.68  4.4      mb  NaN   
8   2021-03-16T15:01:32.010Z    4.2565    97.5425  193.78  4.4      mb  NaN   
9   2021-03-04T23:36:58.479Z    5.0051    96.0004   10.00  4.5      mb  NaN   
10  2021-02-11T15:35:10.916Z    3.5719    96.8983   95.16  4.4      mb  NaN   
11  2021-01-30T09:06:44.294Z    4.6586    96.3415   10.00  4.3      mb  NaN   
12  2021-01-26T03:36:36.765Z    4.8138    94.3724   35.00  4.2      mb  NaN   
13  2021-01-12T04:50:54.625Z    3.8565    95.8590   54.96  4.3      mb  NaN   
14  2021-01-08T23:17:13.343Z    5.1995    94.7194   61.29  4.2      mb  NaN   
15  2020-12-16T23:35:53.610Z    4.1091    96.7993   10.00  4.3      mb  NaN   
16  2020-12-14T14:02:43.159Z    4.4477    96.3535    6.23  4.9      mb  NaN   
17  2020-12-03T03:50:58.767Z    4.5375    97.7230   10.00  4.8      mb  NaN   
18  2020-11-30T17:14:12.006Z    3.0670    96.1349   27.89  5.0      mb  NaN   
19  2020-11-28T23:47:33.748Z    5.3123    94.5032   64.82  4.9      mb  NaN   
20  2020-11-13T18:33:07.130Z    5.7913    95.5619   10.00  5.1     mww  NaN   
21  2020-10-26T12:06:08.133Z    3.3538    95.4990   35.00  4.1      mb  NaN   
22  2020-10-15T04:59:52.829Z    3.9446    95.8698   48.83  4.9     mww  NaN   
23  2020-10-11T11:09:24.305Z    4.5136    96.6797  154.36  4.7      mb  NaN   
24  2020-10-10T20:22:27.940Z    4.7367    95.6557   89.03  4.5      mb  NaN   
25  2020-09-30T18:44:29.341Z    3.6568    97.0207   54.08  4.4      mb  NaN   
26  2020-09-29T10:48:54.148Z    3.9044    97.6847   35.00  4.4      mb  NaN   
27  2020-09-29T03:00:39.159Z    3.0780    96.7648   35.00  4.2      mb  NaN   
28  2020-09-28T18:16:11.571Z    3.9397    97.6972   35.00  4.2      mb  NaN   
29  2020-09-24T09:34:06.486Z    5.2464    96.6839  218.55  4.1      mb  NaN   
30  2020-09-19T04:50:22.414Z    4.9746    96.4066   10.00  4.5      mb  NaN   
31  2020-09-18T10:15:20.553Z    5.2039    94.7511   76.44  4.5      mb  NaN   
32  2020-09-13T18:28:52.194Z    4.2449    96.6838  121.54  5.0     mww  NaN   
33  2020-09-01T11:52:50.668Z    3.0422    95.7332    8.51  4.9      mb  NaN   
34  2020-08-20T13:53:52.144Z    4.8884    96.0874   10.00  4.4      mb  NaN   
35  2020-08-06T10:12:56.849Z    3.7417    95.6192   43.50  4.6      mb  NaN   
36  2020-06-18T10:56:55.720Z    5.7719    95.2875   10.00  4.5      mb  NaN   
37  2020-06-10T04:23:22.554Z    3.5269    98.0192  140.62  4.3      mb  NaN   
38  2020-06-05T01:23:03.458Z    4.5025    95.1232   50.69  4.5      mb  NaN   
39  2020-06-03T22:30:55.044Z    5.6736    95.1700   10.00  4.6      mb  NaN   
40  2020-05-25T10:08:11.583Z    4.9608    94.4496   48.36  4.5      mb  NaN   

    gap   dmin   rms  ...                   updated  \
0   132  2.322  0.87  ...  2021-05-02T21:02:32.040Z   
1   129  1.669  0.86  ...  2021-05-09T13:22:24.040Z   
2    50  1.494  1.13  ...  2021-04-17T02:23:46.858Z   
3   167  0.799  1.01  ...  2021-04-25T16:21:42.040Z   
4   173  2.127  0.48  ...  2021-04-23T04:41:16.040Z   
5    95  1.850  0.82  ...  2021-05-05T14:02:32.040Z   
6   178  1.278  0.58  ...  2021-04-20T03:21:44.040Z   
7    98  2.537  0.91  ...  2021-04-16T12:30:49.040Z   
8    98  1.133  0.75  ...  2021-04-21T13:17:34.040Z   
9   174  0.968  0.97  ...  2021-05-13T22:45:52.040Z   
10  155  1.646  0.64  ...  2021-04-22T21:53:32.040Z   
11  152  0.827  0.41  ...  2021-04-16T19:03:3

We can show the first-five of data by using `[variable].head()` as follows

In [ ]:
data.head()

time  latitude  longitude   depth  mag magType  nst  \
0  2021-05-02T20:49:43.322Z    5.3234    94.6170   63.97  5.0      mb  NaN   
1  2021-05-02T13:02:17.751Z    4.0461    95.7566   50.03  4.6      mb  NaN   
2  2021-04-17T01:04:53.776Z    5.1158    95.4508  100.74  5.0     mww  NaN   
3  2021-04-09T15:14:31.108Z    4.8116    96.2611   27.57  4.3      mb  NaN   
4  2021-04-09T08:08:58.946Z    3.0723    96.3738   55.17  4.2      mb  NaN   

   gap   dmin   rms  ...                   updated  \
0  132  2.322  0.87  ...  2021-05-02T21:02:32.040Z   
1  129  1.669  0.86  ...  2021-05-09T13:22:24.040Z   
2   50  1.494  1.13  ...  2021-04-17T02:23:46.858Z   
3  167  0.799  1.01  ...  2021-04-25T16:21:42.040Z   
4  173  2.127  0.48  ...  2021-04-23T04:41:16.040Z   

                                place        type horizontalError depthError  \
0  82 km WSW of Banda Aceh, Indonesia  earthquake             9.6        7.6   
1    42 km WSW of Meulaboh, Indonesia  earthquake             7.6        8.2   
2  48 km SSE of Banda Aceh, Indonesia  earthquake             8.2        6.3   
3      44 km S of Reuleuet, Indonesia  earthquake             5.9        5.9   
4      65 km N of Sinabang, Indonesia  earthquake             7.4        9.2   

   magError  magNst    status  locationSource magSource  
0     0.099      32  reviewed              us        us  
1     0.136      16  reviewed              us        us  
2     0.098      10  reviewed              us        us  
3     0.153      14  reviewed              us        us  
4     0.121      19  reviewed              us        us  

[5 rows x 22 columns]

#### Get an Information File

As we can see, there is a lot of data that we are dealing with. We can see a short information from this file by using `[variable].info()` method as follows

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   time             41 non-null     object 
 1   latitude         41 non-null     float64
 2   longitude        41 non-null     float64
 3   depth            41 non-null     float64
 4   mag              41 non-null     float64
 5   magType          41 non-null     object 
 6   nst              0 non-null      float64
 7   gap              41 non-null     int64  
 8   dmin             41 non-null     float64
 9   rms              41 non-null     float64
 10  net              41 non-null     object 
 11  id               41 non-null     object 
 12  updated          41 non-null     object 
 13  place            41 non-null     object 
 14  type             41 non-null     object 
 15  horizontalError  41 non-null     float64
 16  depthError       41 non-null     float64
 17  magError         4

Here we are. Through this information, we can conclude there are:

- 22 columns of data
- 41 rows of data
- The column of `nst` does not has a data (0 non-null) or NaN
- three types data: object, int64  and float64

We can easily to find out that how many dimension does this data have by using `[variable].shape` method

In [ ]:
data.shape

(41, 22)

#### Remove a Certain Data

Because the column of `nst` has a NaN data, we can remove this column and assign to new variable of `new_data`. To remove, we can apply

In [ ]:
new_data = data.drop('nst',axis=1)

In [ ]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   time             41 non-null     object 
 1   latitude         41 non-null     float64
 2   longitude        41 non-null     float64
 3   depth            41 non-null     float64
 4   mag              41 non-null     float64
 5   magType          41 non-null     object 
 6   gap              41 non-null     int64  
 7   dmin             41 non-null     float64
 8   rms              41 non-null     float64
 9   net              41 non-null     object 
 10  id               41 non-null     object 
 11  updated          41 non-null     object 
 12  place            41 non-null     object 
 13  type             41 non-null     object 
 14  horizontalError  41 non-null     float64
 15  depthError       41 non-null     float64
 16  magError         41 non-null     float64
 17  magNst           4

The number of columns has been changed to 21 columns. The axis=1 indicates for column section and axis=0 for row section. Alternative way, if we do not to asign a new variable or just keep the original variable after we remove a certain data, we can add an attribute of `inplace=True` in `[variable].drop()` command as follows:

In [ ]:
data.drop('nst', axis=1, inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   time             41 non-null     object 
 1   latitude         41 non-null     float64
 2   longitude        41 non-null     float64
 3   depth            41 non-null     float64
 4   mag              41 non-null     float64
 5   magType          41 non-null     object 
 6   gap              41 non-null     int64  
 7   dmin             41 non-null     float64
 8   rms              41 non-null     float64
 9   net              41 non-null     object 
 10  id               41 non-null     object 
 11  updated          41 non-null     object 
 12  place            41 non-null     object 
 13  type             41 non-null     object 
 14  horizontalError  41 non-null     float64
 15  depthError       41 non-null     float64
 16  magError         41 non-null     float64
 17  magNst           4

For next case, we use `new_data` variable to explore more methods from Pandas library.

#### Select Some of Data

By using Pandas, we can select some of data and assign to new variable. For example, we want to take the data of `time`, `latitude`,`longitude`,`depth`,`mag`,`magType` and `place`. These data are assigned to `current_data` variable. To do this,

In [ ]:
current_data = new_data[['time','latitude','longitude','depth','mag','magType','place']]

In [ ]:
current_data.head()

time  latitude  longitude   depth  mag magType  \
0  2021-05-02T20:49:43.322Z    5.3234    94.6170   63.97  5.0      mb   
1  2021-05-02T13:02:17.751Z    4.0461    95.7566   50.03  4.6      mb   
2  2021-04-17T01:04:53.776Z    5.1158    95.4508  100.74  5.0     mww   
3  2021-04-09T15:14:31.108Z    4.8116    96.2611   27.57  4.3      mb   
4  2021-04-09T08:08:58.946Z    3.0723    96.3738   55.17  4.2      mb   

                                place  
0  82 km WSW of Banda Aceh, Indonesia  
1    42 km WSW of Meulaboh, Indonesia  
2  48 km SSE of Banda Aceh, Indonesia  
3      44 km S of Reuleuet, Indonesia  
4      65 km N of Sinabang, Indonesia

#### Modify an Attribute of Data

##### Rename a Column Name
We can modify an attribute of data, such as to rename a old column name to new column name. For example, we change all column names as follows

In [ ]:
current_data = current_data.rename(columns={
    'time':'Time',
    'latitude':'Latitude',
    'longitude':'Longitude',
    'depth':'Depth',
    'mag':'Mag',
    'magType':'MagType',
    'place':'Place'
})

In [ ]:
current_data.head()

Time  Latitude  Longitude   Depth  Mag MagType  \
0  2021-05-02T20:49:43.322Z    5.3234    94.6170   63.97  5.0      mb   
1  2021-05-02T13:02:17.751Z    4.0461    95.7566   50.03  4.6      mb   
2  2021-04-17T01:04:53.776Z    5.1158    95.4508  100.74  5.0     mww   
3  2021-04-09T15:14:31.108Z    4.8116    96.2611   27.57  4.3      mb   
4  2021-04-09T08:08:58.946Z    3.0723    96.3738   55.17  4.2      mb   

                                Place  
0  82 km WSW of Banda Aceh, Indonesia  
1    42 km WSW of Meulaboh, Indonesia  
2  48 km SSE of Banda Aceh, Indonesia  
3      44 km S of Reuleuet, Indonesia  
4      65 km N of Sinabang, Indonesia

##### Change a String Format
Let's moving on. We see that the content in the `MagType` indicates the unit of earthquake scale. All units are written in lowercase. So, if we want to change these contents to capitalize (uppercase or lowercase), we can use `[variable].str.capitalize` method. First, we  have to select the content of `MagType` column

In [ ]:
current_data['MagType'] = current_data['MagType'].str.capitalize()
current_data.head()

Time  Latitude  Longitude   Depth  Mag MagType  \
0  2021-05-02T20:49:43.322Z    5.3234    94.6170   63.97  5.0      Mb   
1  2021-05-02T13:02:17.751Z    4.0461    95.7566   50.03  4.6      Mb   
2  2021-04-17T01:04:53.776Z    5.1158    95.4508  100.74  5.0     Mww   
3  2021-04-09T15:14:31.108Z    4.8116    96.2611   27.57  4.3      Mb   
4  2021-04-09T08:08:58.946Z    3.0723    96.3738   55.17  4.2      Mb   

                                Place  
0  82 km WSW of Banda Aceh, Indonesia  
1    42 km WSW of Meulaboh, Indonesia  
2  48 km SSE of Banda Aceh, Indonesia  
3      44 km S of Reuleuet, Indonesia  
4      65 km N of Sinabang, Indonesia

The change a content to capitalize (upper or lower), that just can be applied to `string` variable type. In this case the type of `MagType` variable is `string` or commonly is mentioned as `object`.

##### Time Modification

In the `Time` variable, the time is written as `object` type. We can convert it to time format by using `pd.to_datetime(dataframe)`

In [ ]:
current_data['Time'] = pd.to_datetime(current_data['Time'])
current_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype              
---  ------     --------------  -----              
 0   Time       41 non-null     datetime64[ns, UTC]
 1   Latitude   41 non-null     float64            
 2   Longitude  41 non-null     float64            
 3   Depth      41 non-null     float64            
 4   Mag        41 non-null     float64            
 5   MagType    41 non-null     object             
 6   Place      41 non-null     object             
dtypes: datetime64[ns, UTC](1), float64(4), object(2)
memory usage: 2.4+ KB


In [ ]:
current_data.head()

Time  Latitude  Longitude   Depth  Mag MagType  \
0 2021-05-02 20:49:43.322000+00:00    5.3234    94.6170   63.97  5.0      Mb   
1 2021-05-02 13:02:17.751000+00:00    4.0461    95.7566   50.03  4.6      Mb   
2 2021-04-17 01:04:53.776000+00:00    5.1158    95.4508  100.74  5.0     Mww   
3 2021-04-09 15:14:31.108000+00:00    4.8116    96.2611   27.57  4.3      Mb   
4 2021-04-09 08:08:58.946000+00:00    3.0723    96.3738   55.17  4.2      Mb   

                                Place  
0  82 km WSW of Banda Aceh, Indonesia  
1    42 km WSW of Meulaboh, Indonesia  
2  48 km SSE of Banda Aceh, Indonesia  
3      44 km S of Reuleuet, Indonesia  
4      65 km N of Sinabang, Indonesia

We can separate the `Time` for each time format, such as year, month and date. To do this, We assign to new column for each time format.

In [ ]:
current_data['Year'] = current_data['Time'].dt.year
current_data['Month'] = current_data['Time'].dt.month
current_data['Day'] = current_data['Time'].dt.day
current_data['Hour'] = current_data['Time'].dt.hour
current_data['Minutes'] = current_data['Time'].dt.minute
current_data['Second'] = current_data['Time'].dt.second

In [ ]:
current_data.head()

Time  Latitude  Longitude   Depth  Mag MagType  \
0 2021-05-02 20:49:43.322000+00:00    5.3234    94.6170   63.97  5.0      Mb   
1 2021-05-02 13:02:17.751000+00:00    4.0461    95.7566   50.03  4.6      Mb   
2 2021-04-17 01:04:53.776000+00:00    5.1158    95.4508  100.74  5.0     Mww   
3 2021-04-09 15:14:31.108000+00:00    4.8116    96.2611   27.57  4.3      Mb   
4 2021-04-09 08:08:58.946000+00:00    3.0723    96.3738   55.17  4.2      Mb   

                                Place  Year  Month  Day  Hour  Minutes  Second  
0  82 km WSW of Banda Aceh, Indonesia  2021      5    2    20       49      43  
1    42 km WSW of Meulaboh, Indonesia  2021      5    2    13        2      17  
2  48 km SSE of Banda Aceh, Indonesia  2021      4   17     1        4      53  
3      44 km S of Reuleuet, Indonesia  2021      4    9    15       14      31  
4      65 km N of Sinabang, Indonesia  2021      4    9     8        8      58

##### Data Sorting

By using pandas, we can sort a data from minimum to maximum or vice versa. For example, we sort the `Mag` variable fro maximum to minimum.

In [ ]:
current_data.sort_values(by='Mag', ascending=False, inplace = True)

In [ ]:
current_data.head()

Time  Latitude  Longitude   Depth  Mag MagType  \
20 2020-11-13 18:33:07.130000+00:00    5.7913    95.5619   10.00  5.1     Mww   
18 2020-11-30 17:14:12.006000+00:00    3.0670    96.1349   27.89  5.0      Mb   
32 2020-09-13 18:28:52.194000+00:00    4.2449    96.6838  121.54  5.0     Mww   
0  2021-05-02 20:49:43.322000+00:00    5.3234    94.6170   63.97  5.0      Mb   
2  2021-04-17 01:04:53.776000+00:00    5.1158    95.4508  100.74  5.0     Mww   

                                 Place  Year  Month  Day  Hour  Minutes  \
20      29 km ESE of Sabang, Indonesia  2020     11   13    18       33   
18    70 km NNW of Sinabang, Indonesia  2020     11   30    17       14   
32      62 km E of Meulaboh, Indonesia  2020      9   13    18       28   
0   82 km WSW of Banda Aceh, Indonesia  2021      5    2    20       49   
2   48 km SSE of Banda Aceh, Indonesia  2021      4   17     1        4   

    Second  
20       7  
18      12  
32      52  
0       43  
2       53

The data has been sorted. As we can see, the index number has been changed to. So, we have to reset the index number as follows

In [ ]:
current_data.reset_index(inplace=True)

In [ ]:
current_data.head()

index                             Time  Latitude  Longitude   Depth  Mag  \
0     20 2020-11-13 18:33:07.130000+00:00    5.7913    95.5619   10.00  5.1   
1     18 2020-11-30 17:14:12.006000+00:00    3.0670    96.1349   27.89  5.0   
2     32 2020-09-13 18:28:52.194000+00:00    4.2449    96.6838  121.54  5.0   
3      0 2021-05-02 20:49:43.322000+00:00    5.3234    94.6170   63.97  5.0   
4      2 2021-04-17 01:04:53.776000+00:00    5.1158    95.4508  100.74  5.0   

  MagType                               Place  Year  Month  Day  Hour  \
0     Mww      29 km ESE of Sabang, Indonesia  2020     11   13    18   
1      Mb    70 km NNW of Sinabang, Indonesia  2020     11   30    17   
2     Mww      62 km E of Meulaboh, Indonesia  2020      9   13    18   
3      Mb  82 km WSW of Banda Aceh, Indonesia  2021      5    2    20   
4     Mww  48 km SSE of Banda Aceh, Indonesia  2021      4   17     1   

   Minutes  Second  
0       33       7  
1       14      12  
2       28      52  
3       49      43  
4        4      53

Then, we remove the old index column

In [ ]:
current_data.drop('index',axis=1,inplace=True)

In [ ]:
current_data.head()

Time  Latitude  Longitude   Depth  Mag MagType  \
0 2020-11-13 18:33:07.130000+00:00    5.7913    95.5619   10.00  5.1     Mww   
1 2020-11-30 17:14:12.006000+00:00    3.0670    96.1349   27.89  5.0      Mb   
2 2020-09-13 18:28:52.194000+00:00    4.2449    96.6838  121.54  5.0     Mww   
3 2021-05-02 20:49:43.322000+00:00    5.3234    94.6170   63.97  5.0      Mb   
4 2021-04-17 01:04:53.776000+00:00    5.1158    95.4508  100.74  5.0     Mww   

                                Place  Year  Month  Day  Hour  Minutes  Second  
0      29 km ESE of Sabang, Indonesia  2020     11   13    18       33       7  
1    70 km NNW of Sinabang, Indonesia  2020     11   30    17       14      12  
2      62 km E of Meulaboh, Indonesia  2020      9   13    18       28      52  
3  82 km WSW of Banda Aceh, Indonesia  2021      5    2    20       49      43  
4  48 km SSE of Banda Aceh, Indonesia  2021      4   17     1        4      53